services:

  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    container_name: articles_postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres:/data/postgres
  adminer:
    image: adminer
    container_name: articles_adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - "${ADMINER_PORT}:8080"
  redis:
    image: redis:7-alpine
    container_name: articles_redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD} --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    env_file:
      - .env
volumes:
  postgres:
  redis_data:
    driver: local
